name: tristan
channels:
  - conda-forge
  - defaults
dependencies:
  # Core packages installed via Conda
  - python=3.10
  - pandas=2.3.3
  - numpy=2.2.5
  - matplotlib=3.10.6
  - pingouin=0.5.5
  - dask=2025.5.1
  - pip=25.3
  
  # Pip-only packages
  - pip:
      - -r hpc_requirements.txt